import meal1 from '../assets/meals/meal (1).jpg';
import meal2 from '../assets/meals/meal (2).jpg';
import meal3 from '../assets/meals/meal (3).jpg';
import meal4 from '../assets/meals/meal (4).jpg';
import meal5 from '../assets/meals/meal (5).jpg';
import meal6 from '../assets/meals/meal (6).jpg';
import meal7 from '../assets/meals/meal (7).jpg';
import meal8 from '../assets/meals/meal (8).jpg';
import meal9 from '../assets/meals/meal (9).jpg';
import meal10 from '../assets/meals/meal (10).jpg';
import meal11 from '../assets/meals/meal (11).jpg';
import meal12 from '../assets/meals/meal (12).jpg';
import meal14 from '../assets/meals/meal (14).jpg';
import meal15 from '../assets/meals/meal (15).jpg';
import meal16 from '../assets/meals/meal (16).jpg';
import meal17 from '../assets/meals/meal (17).jpg';
import meal18 from '../assets/meals/meal (18).jpg';
import meal19 from '../assets/meals/meal (19).jpg';
import meal20 from '../assets/meals/meal (20).jpg';
import meal21 from '../assets/meals/meal (21).jpg';
import meal22 from '../assets/meals/meal (22).jpg';
import meal23 from '../assets/meals/meal (24).jpg';
import meal24 from '../assets/meals/meal (24).jpg';
import meal25 from '../assets/meals/meal (25).jpg';
import meal26 from '../assets/meals/meal (26).jpg';
import meal27 from '../assets/meals/meal (27).jpg';
import meal28 from '../assets/meals/meal (28).jpg';
import meal29 from '../assets/meals/meal (29).jpg';
import meal30 from '../assets/meals/meal (30).jpg';
import meal31 from '../assets/meals/meal (31).jpg';
import meal32 from '../assets/meals/meal (32).jpg';
import meal33 from '../assets/meals/meal (33).jpg';

export const meals = [
  // Repeating the structure for each meal from 1 to 33
  {
    id: 1,
    image: meal1,
    en_name: 'meal1',
    fr_name: 'repas1',
    en_ingredients: ['ingredient1-1', 'ingredient1-2', 'ingredient1-3'],
    fr_ingredients: ['ingrédient1-1', 'ingrédient1-2', 'ingrédient1-3'],
    en_extra: 'extra1',
    fr_extra: 'extra1',
    price: 200,
    rate: 4.1,
  },
  {
    id: 2,
    image: meal2,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal3,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal4,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal15,
    en_name: 'Steak Philadelphie ',
    fr_name: 'Philadelphia Steak',
    en_ingredients: [
      'Tender beef slices',
      'bell pepper',
      'grilled onion',
      'mushrooms',
      ' pepper corn mayo sauce',
    ],
    fr_ingredients: [
      'Tranches de bœuf tendre',
      'mozzarella',
      'poivrons',
      'oignons',
      'champignons',
      'mayonnaise au poivre',
    ],
    en_extra: '',
    fr_extra: '',
    price: 13.99,
    rate: 4.2,
  },

  {
    id: 2,
    image: meal6,
    en_name: 'Buffalo Crispy Chicken',
    fr_name: 'Poulet Buffalo Croustillant',
    en_ingredients: ['Spicy', 'Buffalo chicken strips', 'lettuce and mayo'],
    fr_ingredients: [
      'Épicé',
      'Languettes de poulet',
      'salade de chou',
      ' frites et mayo',
    ],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal7,
    en_name: 'Buffalo Crispy Chicken',
    fr_name: 'Poulet Buffalo Croustillant',
    en_ingredients: ['Spicy', 'Buffalo chicken strips', 'lettuce and mayo'],
    fr_ingredients: [
      'Épicé',
      'Languettes de poulet',
      'salade de chou',
      ' frites et mayo',
    ],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal8,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal9,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal10,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal11,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal12,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },

  {
    id: 2,
    image: meal14,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal5,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal16,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal17,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal18,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal19,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal20,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal21,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal22,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal23,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal24,
    en_name: 'meal2',
    fr_name: 'repas2',
    en_ingredients: ['ingredient2-1', 'ingredient2-2', 'ingredient2-3'],
    fr_ingredients: ['ingrédient2-1', 'ingrédient2-2', 'ingrédient2-3'],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal25,
    en_name: 'Milkshakes',
    fr_name: 'Lait Frappé',
    en_ingredients: [' With whipped cream'],
    fr_ingredients: ['Avec de la crème fouettée. '],
    en_extra: '',
    fr_extra: '',
    price: 7.99,
    rate: 4.2,
  },

  {
    id: 2,
    image: meal27,
    en_name: 'Milkshakes',
    fr_name: 'Lait Frappé',
    en_ingredients: [' With whipped cream'],
    fr_ingredients: ['Avec de la crème fouettée. '],
    en_extra: '',
    fr_extra: '',
    price: 7.99,
    rate: 4.2,
  },
  {
    id: 2,
    image: meal28,
    en_name: 'Milkshakes',
    fr_name: 'Lait Frappé',
    en_ingredients: [' With whipped cream'],
    fr_ingredients: ['Avec de la crème fouettée. '],
    en_extra: '',
    fr_extra: '',
    price: 7.99,
    rate: 4.2,
  },

  {
    id: 2,
    image: meal30,
    en_name: 'Original Crispy Chicken',
    fr_name: 'Poulet Croustillant',
    en_ingredients: [
      'Chicken strips',
      'mayo',
      'corn',
      'pickles',
      'coleslaw',
      'fries',
    ],
    fr_ingredients: [
      'Languettes de poulet',
      'salade de chou',
      'cornichons',
      'frites et mayo',
    ],
    en_extra: 'extra2',
    fr_extra: 'extra2',
    price: 210,
    rate: 4.2,
  },
  {
    id: 31,
    image: meal31,
    en_name: 'Francisco',
    fr_name: 'Francisco',
    en_ingredients: [
      ' Chicken breast fillet',
      'mushrooms',
      'corn',
      'lettuce',
      'mozzarella cheese',
      'mayo',
      'soy sauce',
    ],
    fr_ingredients: [
      'Poitrine de poulet grillée',
      'mozzarella',
      'champignons',
      'maïs',
      'laitue',
      'mayo et soya',
    ],
    en_extra: '',
    fr_extra: '',
    price: 12.99,
    rate: 4.2,
  },
  {
    id: 32,
    image: meal32,
    en_name: ' Special Crispy Chicken',
    fr_name: 'Poulet Croustillant Spécial ',
    en_ingredients: [
      'Chicken strips',
      'mayo',
      'gravy',
      'mozzarella cheese',
      'smoked turkey',
      'fries',
    ],
    fr_ingredients: [
      'Languettes de poulet',
      'mayo',
      'tranches de dinde fumée',
      'mozzarella',
      'frites et sauce brune',
    ],
    en_extra: '',
    fr_extra: '',
    price: 13.99,
    rate: 4.2,
  },
  {
    id: 33,
    image: meal33,
    en_name: 'Fajita',
    fr_name: 'Fajita',
    en_ingredients: [
      'Chicken breast fillet',
      'bell pepper',
      'grilled onion',
      'corn',
      'mozzarella cheese',
      'mayo',
      'soy sauce',
    ],
    fr_ingredients: [
      'Poitrine de poulet grillée',
      'mozzarella',
      'poivrons',
      'oignons',
      'maïs',
      'mayo et soya',
    ],
    en_extra: '',
    fr_extra: '',
    price: 12.99,
    rate: 3.7,
  },
];
